// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecrementCounter(arg1:number):Promise<number>;

export function GetCounter(arg1:number):Promise<number>;

export function IncrementCounter(arg1:number):Promise<number>;
