// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecrementCounter(arg1) {
  return window['go']['main']['App']['DecrementCounter'](arg1);
}

export function GetCounter(arg1) {
  return window['go']['main']['App']['GetCounter'](arg1);
}

export function IncrementCounter(arg1) {
  return window['go']['main']['App']['IncrementCounter'](arg1);
}
